dist: trusty
language: php
services:
  - mysql
cache:
  apt: true
env:
  global:
  - EE_VERSION=master
    - WP_VERSION=latest
  matrix:
  - WP_MULTISITE=0
  - WP_MULTISITE=1
php:
- 7.1
- 7.2
- 7.3
- 7.4
matrix:
  exclude:
  - php: 7.1
    env: WP_MULTISITE=1
  - php: 7.2
    env: WP_MULTISITE=1
  - php: 7.3
    env: WP_MULTISITE=1
  fast_finish: true
before_install:
- composer install || exit 1
- composer global require phpunit/phpunit ^7
before_script:
- bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- . tests/bin/setup-addon-tests.sh
- mysql --version
- phpenv versions
- phpunit --version
script: cd tests; phpunit;
notifications:
  slack:
    rooms:
      secure: cVmCG8hUp59UAdx3OBmEweIVqKUr1sYhnWGCdRiylUJtSTP+ehSpfsNLZLfv1ntNlTlA/Iw+8bQbKOeRYCyuWA1FQ7QdZ3Y66jRpyT3AXcT+oKomGogKFY2yLQt2P58uXIyVVt8H9U4xrAM8t8gvARq7asUtbOGnt+1LbbHhUXKXiB6PLkRdGSSL/jFJKLfYyzfD0r43KTYl1e9MhpbO6nzPKGz2vejtA8sdTsfiOj7tQqyf9xydz51PlSic2YWwYoSMH9SjkQX+mPBz7JQHhJiZ9srh0AyVPZDNe03bTUv1D8ICuS7nqQYXpa3RePD12IA4nCvKG/Akn2pxrJtDQPuiYpTyjvuDvgNbg/ET86WBUjvzKKbZYP5QDx7XFf38NdUw9NjfqYR6pJzoX3dPXXwgRHLATBqjlZ4xKHKkUBWxJO8asCkUKDb9/bvjGxL057IqpWmVemmK44uwtPSdw9ml46PakWdbXq3KKtWM6VESFakCsw17O88csywUcPuACHlFUjWTUq9bUsq3ZNryezAfeg4b0Pbwr1JIqt0kOE2yc4YF6TOH+XKIuKS8dLvSqiCHUNstGOSu5DzqsIi5qDUIGn6QHumVc7wFC8o3Db7Fcq1zcFMsWB4t0cm15ZDc1uyBR9QkM8svN8oPYjimEJpYc3nn8kRwmzZm3bemBzk=
    on_success: change
    on_failure: always
    on_start: always
