dist: trusty

language: php

services:
  - mysql

cache:
  apt: true
#  directories:
#    - $HOME/.composer/cache

env:
  global:
    - EE_VERSION=master
    - EE_BRANCH=barista-prod
    - BRANCH=barista-prod
    - WP_VERSION=latest
    - WP_MULTISITE=0

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # Unless we need XDebug, disable it for improved performance.
  - phpenv config-rm xdebug.ini || return 0

install:
  # Install our Composer dependencies
  - composer install --prefer-dist --no-interaction || exit 1
#  - composer global require "phpunit/phpunit=7.5.*"
  # Install the WordPress core test suite
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - . tests/bin/setup-addon-tests.sh
  - mysql --version
  - phpunit --version

before_script:
  - phpenv versions

script: cd tests; phpunit;

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.4
      env:
        - PHP_LINT=1
      script:
        - composer config-eventespressocs || exit 1
        - composer run-script lint:skip-warnings || exit 1
    - php: 7.4
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.4
      env:
        - WP_MULTISITE=1
    - php: nightly

notifications:
  slack:
    rooms:
      secure: cVmCG8hUp59UAdx3OBmEweIVqKUr1sYhnWGCdRiylUJtSTP+ehSpfsNLZLfv1ntNlTlA/Iw+8bQbKOeRYCyuWA1FQ7QdZ3Y66jRpyT3AXcT+oKomGogKFY2yLQt2P58uXIyVVt8H9U4xrAM8t8gvARq7asUtbOGnt+1LbbHhUXKXiB6PLkRdGSSL/jFJKLfYyzfD0r43KTYl1e9MhpbO6nzPKGz2vejtA8sdTsfiOj7tQqyf9xydz51PlSic2YWwYoSMH9SjkQX+mPBz7JQHhJiZ9srh0AyVPZDNe03bTUv1D8ICuS7nqQYXpa3RePD12IA4nCvKG/Akn2pxrJtDQPuiYpTyjvuDvgNbg/ET86WBUjvzKKbZYP5QDx7XFf38NdUw9NjfqYR6pJzoX3dPXXwgRHLATBqjlZ4xKHKkUBWxJO8asCkUKDb9/bvjGxL057IqpWmVemmK44uwtPSdw9ml46PakWdbXq3KKtWM6VESFakCsw17O88csywUcPuACHlFUjWTUq9bUsq3ZNryezAfeg4b0Pbwr1JIqt0kOE2yc4YF6TOH+XKIuKS8dLvSqiCHUNstGOSu5DzqsIi5qDUIGn6QHumVc7wFC8o3Db7Fcq1zcFMsWB4t0cm15ZDc1uyBR9QkM8svN8oPYjimEJpYc3nn8kRwmzZm3bemBzk=
    on_success: change
    on_failure: always
    on_start: always
